# Generated by Django 4.2.2 on 2023-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
